### ISSUE TITLE
Android devices keep reconnecting when screen is turned off

### ISSUE THREAD

**Issue by ookke** [primus/primus#350]
This is a similar issue to https://github.com/primus/primus/issues/348

Basically it seems that Chrome on Android will leave websockets open but it will suspend timers completely when the screen is turned off. This causes the device to get disconnected when the heartbeat times out on the server side and it will keep reconnecting and getting disconnected because the heartbeat timer is not running on the client side.

This is not a major issue but it still spams our logs with unnecessary reconnects and it will also affect our users battery life a bit I guess.

Some random ideas:

a) Run a "are we sleeping" timer that updates a timestamp every x seconds, if last timestamp is > x seconds ago we know that the device is probably sleeping and we don't need to bother reconnecting until we are awake again. Awake can be similarly triggered when we notice that the setInterval is firing again after a delay.

b) Apparently timers in webworkers are immune to suspend/tab in background to some degree: http://stackoverflow.com/a/12522580 so in theory at least we could use webworkers for more reliable timers when available, haven't tested if this is valid for mobile devices though.

**Comment by 3rd-Eden** [comment]
The question here is what is the best approach for this. When a user is background your application, you do you still want data to flow or is it ok to keep the connection closed and re-open when it's activated again (you can use the timers hack you suggested, the visibility api of browser and the focus/blur events). For stock updates or movie, audio streaming and a chatbox I can assume that you want to keep the connection open against all costs as you might lose sound or valuable state.

While webworkers do fix the issues in browsers the problem is that it does come with a fair amount of overhead as you need to ship another file which implements timer logic and you're basically running 2 vms which can consume more memory of the device then a simple reconnect process.

Luckly when we decide to fix this problem it would be relatively easy to do so. If we go for connection open all the times we only have to update our internal timer management module with some addition hacks :p. Any thoughts on this @ookke @lpinca & others?

**Comment by lpinca** [comment]
I don't know, i guess it really depends on the device and the app, for this reason if this could be handled outside of Primus it would be better imho.

**Comment by 3rd-Eden** [comment]
@lpinca I was just thinking of introducing yet another option in the Primus client like `{ background: true }` to force this thing to do a best effort of keeping the connection alive while backgrounded.

**Comment by lpinca** [comment]
I'm fine with that.

**Comment by ookke** [comment]
A configurable option sounds like a flexible solution, for our app it is not currently critical to maintain the connection while in the background but would still be good to have the choice I think.

**Comment by akreienbring** [comment]
+1 as I rely on permanent server connection to receive messages.
for the interesested cordova/angular users:
1, https://github.com/katzer/cordova-plugin-background-mode (keeps network connections alive in background.
2. https://github.com/aharris88/phonegap-powerManagement-plugin (aquire a partial wakelock)

**Comment by 3rd-Eden** [comment]
Bumped priority on this bug.

**Comment by puzrin** [comment]
https://github.com/nodeca/tabex/issues/5

### Timers at mobile devices

| Browser | Background | Display off | Background WW | Display off WW |
| ------- | ---------- | ----------- | ------------- | -------------- |
| Android browser | OK | fail | OK | fail |
| Android FF | fail | fail | OK | OK |
| Android Chrome | OK | OK | OK | OK |
| iOS Chrome | OK | fail | OK | fail |
| iOS Safari | fail | fail | fail | fail |

* iOS Safari - some times timer in background can continue working 0-20 seconds
* iOS Safari - foreground tab continue working 10-15 seconds then display is turned off

It seems, problem is not fixable on ios at all. WW should help with android in major browsers.

**Comment by 3rd-Eden** [comment]
@puzrin we just don't know if this something that should be fixed in primus as just running primus in a WebWorker will fix this issue.

**Comment by puzrin** [comment]
@3rd-Eden did i missed something? I did not found proofs, that primus will be better in webworkers, only suggestions. It will need timers too, and as far as i see, ww timers will be better in Android FF, but still not working in ios. Also, in ios problem exists even in background tab (when display is on).

**Comment by utan** [comment]
Is this a bug? 

I have that issue in socket.io and thats why i decided to try Primus with sockj as transformer. 
but testing i have the same disconnections..

Whats the best way to have Mobile browsers not disconnect so often, is there a way to do it?

Any ideas?

**Comment by puzrin** [comment]
@utan see https://github.com/primus/primus/issues/350#issuecomment-111218368. I guess, no way on iOS (via timers). May be server-side pings could help, but that requires significant code update.

**Comment by utan** [comment]
I see, but was the "background" property added or was just a comment?
Confused...

**Comment by utan** [comment]
I have to test SockJs alone, I remember i was impressed because i saw no disconnection while playing with it..

I will go back and test it again and see if this has disconnections whitout using Primus..

Will get back with results.

**Comment by lpinca** [comment]
@utan I guess it works with SockJS because it doesn't have a heartbeat system.
You can try to disable the heartbeats on Primus and see if this changes something but that doesn't seem a good idea.
Also take a look at this thread https://github.com/primus/primus/issues/348. Last time I tried I found that timers were delayed by 10s on Safari no matter what the original delay was. Maybe something similar is also done by other mobile browsers.

**Comment by utan** [comment]
@lpinca, 

What's the worst it could happen, get some socket stuck? 

Because I think when the browser disconnects when navigating, closing the tab or browser Primus, will still run disconnected event correct?

regards mate

**Comment by lpinca** [comment]
Yeah, you'll get "zombie" connections and no, there is no `background` option.

**Comment by utan** [comment]
So pretty much this cannot be fixed, a real time application won't work correctly in mobile devices browsers...

and more than 50% of current users are in mobile devices..  and no they don't want to install an app and use it.. the versatility of mobile browser is what attract them...

**Comment by puzrin** [comment]
> What's the worst could happen, get some sockets stuck?

In theory, connection can live infinite time. In real world - ISP can terminate inactive ones, especially on mobiles. And you will not be able to understand if there are no data or connection was broken.

**Comment by puzrin** [comment]
> So pretty much this cannot be fixed, a real time application won't work correctly in mobile devices browsers...

You can write sending pings from server "manually". That's not convenient, but possible. This issue exists because such feature should be built-it.

**Comment by utan** [comment]
@puzrin,
 
Primus already have ping pong or heartbeat, but it still fails.. so I don't really understand what you mean..

It seems the mobile browser, stop Javascript when screen go off or when go to sleep and pings or heartbeat won't work because there is no response back to the server.. if understood correctly.

**Comment by puzrin** [comment]
@utan Look carefully previous explanations. Existing pings are sent from client, are timer-based and not fixable on all devices. It's better to send pings from server, in reverse direction. Then there will be no dependency on timers.

**Comment by lpinca** [comment]
@utan what @puzrin is trying to say is that you can try to reverse the order of ping/pong.
Right now they are sent from client to server and the connection is killed server-side because a ping is not sent.

You can try to disable default heartbeats system and send pings from server to client.

**Comment by utan** [comment]
@puzrin, 

Correct, implement it the other way around... but if the client is not responding because it screen is off or went to sleep, the ping sent from server won't receive a response right..?

Either way if Javascript is freezed by the mobile device it won't do much... until awaken..

**Comment by lpinca** [comment]
@utan it depends if the issue is only with timers then it should work. If the whole JavaScript is freezed then it's pointless.

**Comment by puzrin** [comment]
frozen timers !== frozen js. Network events can be still ok.

**Comment by utan** [comment]
@lpinca, 

I read somewhere don't remember the source, that if the mobile device go to sleep or screen turn off the Jacascript stop functioning , it is something similar like calling the method prompt(); and don't close or accept it javascript freezes any other code after that line where is was invoked...

**Comment by utan** [comment]
I am testing Primus when timeout disabled.. it hasn't disconnected and if I refresh mobile browser the disconnect event is fired properly..

**Comment by 3rd-Eden** [comment]
Pff, times like these I wish I had `git` installed in my brain so I could lookup the history of my thoughts when I added it client side instead of server side. I'm pretty sure I had a valid reason for it, but I just don't know why anymore.

**Comment by utan** [comment]
@3rd-Eden,

I am sure u had, but now is obsolete...

**Comment by lpinca** [comment]
Closing this as heartbeat messages are now initiated by the server. Please comment if the issue persists.

**Comment by ShraddhaGadesha** [comment]
When I load url into webview it's connected to the server.But When I lock the screen Its disconnected .What should I do?
